import {test,expect} from "@playwright/test";
test.beforeEach(async({page})=>{await page.goto("/");await page.evaluate(()=>localStorage.clear());await page.reload()});
test("navigation modules render without error",async({page})=>{for(const name of ["Secretary","Contacts","Customers","Projects","Project Details","Progress","Activity","Files","Documents","Checklist","Estimates","Invoices","Contracts","Change Orders","Approvals","Blueprints","Permits","Receipts","Schedule","Notes","AI Credits","Banking","Settings"]){await page.getByRole("button",{name,exact:true}).click();await expect(page.locator("body")).toContainText(name==="Files"?"Project File Cabinet":name==="Documents"?"Document Center":name==="Progress"?"Project Progress":name==="Activity"?"Activity":name==="Checklist"?"Office Checklist":name==="Invoices"?"Invoice Builder":name==="Contracts"?"Contract Builder":name==="Blueprints"?"Blueprint Workspace":name==="Schedule"?"Job Schedule":name==="Receipts"?"Receipt Tracker":name==="Settings"?"Business Settings":name)}});

test("customer creates separate project folder and secretary can open it",async({page})=>{await page.getByRole("button",{name:"Customers",exact:true}).click();await page.getByPlaceholder("Customer name").fill("Kim");await page.getByPlaceholder("Phone").fill("555-0100");await page.getByPlaceholder("Email").fill("kim@example.com");await page.getByPlaceholder("Project address").fill("123 Main St");await page.getByRole("button",{name:"Save Customer"}).click();await page.getByRole("button",{name:/New Project/}).click();await page.getByPlaceholder("Project name — e.g. Bathroom Remodel").fill("Bathroom Remodel");page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Create Project Folder"}).click();await page.getByRole("button",{name:"Secretary",exact:true}).click();await page.getByRole("button",{name:/Kim/}).click();await expect(page.locator("body")).toContainText("Bathroom Remodel");await page.getByRole("button",{name:/Bathroom Remodel/}).click();await expect(page.locator("body")).toContainText("Contracts");await expect(page.locator("body")).toContainText("Receipts")});

test("estimate calculates and saves",async({page})=>{await page.evaluate(()=>{localStorage.setItem("cohq-customers",JSON.stringify([{id:"c1",name:"Kim",phone:"",email:"",address:""}]));localStorage.setItem("cohq-projects",JSON.stringify([{id:"p1",customerId:"c1",name:"Bathroom Remodel",status:"Lead",total:0,createdAt:new Date().toISOString()}]))});await page.reload();await page.getByRole("button",{name:"Estimates",exact:true}).click();const inputs=page.locator(".estimateRow input");await inputs.nth(0).fill("Tile");await inputs.nth(1).fill("2");await inputs.nth(2).fill("50");await expect(page.locator(".estimateFoot")).toContainText("$100.00");page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Save Estimate"}).click();await expect.poll(async()=>page.evaluate(()=>JSON.parse(localStorage.getItem("cohq-estimates")||"[]").length)).toBe(1)});

test("global search opens and finds customer",async({page})=>{await page.evaluate(()=>localStorage.setItem("cohq-customers",JSON.stringify([{id:"c1",name:"Kim",phone:"555",email:"kim@example.com",address:"Detroit"}])));await page.reload();await page.getByRole("button",{name:"Search",exact:true}).click();await page.getByPlaceholder("Search customers and projects...").fill("Kim");await expect(page.locator(".searchResults")).toContainText("Kim")});
